<?php
declare(strict_types=1);
if (!defined('ABSPATH')) { exit; }
$slug=get_post_field('post_name',get_the_ID());
$articles=[
'dacheindeckung-erneuern-zeitpunkt'=>['title'=>'Wann muss eine Dacheindeckung erneuert werden?','intro'=>'Eine pauschale Altersgrenze gibt es nicht. Ob eine Dachdeckung erneuert werden sollte, hängt vom Zustand der Dachfläche, von wiederkehrenden Schäden und von der Funktion des gesamten Aufbaus ab.','sections'=>[['h2'=>'Typische Anzeichen','items'=>['wiederkehrende Undichtigkeiten','viele beschädigte oder verwitterte Ziegel','häufige Reparaturen an derselben Stelle','sichtbare Feuchtigkeitsspuren im Dachraum','lose Ziegel nach Sturmereignissen']],['h2'=>'Was den Umfang bestimmt','p'=>'Der notwendige Umfang ergibt sich aus dem Zustand der Bauteile unter der Dachdeckung: Lattung, Unterdeckung, Dämmung, Dampfbremse und Holzkonstruktion. Sind diese intakt, kann die Erneuerung der äußeren Dachhaut im Mittelpunkt stehen.'],['h2'=>'Praktisches Vorgehen','p'=>'Sinnvoll ist eine Betrachtung des Bestands, bevor Entscheidungen über Material und Leistungsumfang getroffen werden.']]],
'dacheindeckung-oder-dachsanierung'=>['title'=>'Dacheindeckung erneuern oder Dach sanieren – wo liegt der Unterschied?','intro'=>'Beide Begriffe werden oft gleichgesetzt, beschreiben aber unterschiedliche Umfänge.','sections'=>[['h2'=>'Dacheindeckung erneuern','p'=>'Hier steht die äußere Dachhaut im Mittelpunkt: Die vorhandene Deckung wird zurückgebaut, der Untergrund geprüft und eine neue Dacheindeckung montiert.'],['h2'=>'Dachsanierung','p'=>'Eine Sanierung umfasst zusätzlich weitere Bauteile des Dachaufbaus – zum Beispiel Lattung, Unterdeckung, Dämmung, Dampfbremse oder Teile der Holzkonstruktion.'],['h2'=>'Wovon die Entscheidung abhängt','items'=>['Zustand der Unterkonstruktion','Feuchtigkeit im Aufbau','geplante Nutzung des Dachraums','energetische Ziele','vorhandene Anschlüsse und Details']]]],
'undichtes-dach'=>['title'=>'Was tun bei einem undichten Dach?','intro'=>'Dringt Wasser ein, sollte zunächst der Schaden begrenzt und anschließend die Ursache geklärt werden.','sections'=>[['h2'=>'Erste Schritte','items'=>['Wasser auffangen und empfindliche Gegenstände schützen','betroffene Bereiche fotografieren','Strominstallationen im betroffenen Bereich beachten','keine riskanten Arbeiten auf dem Dach durchführen']],['h2'=>'Ursachen sind nicht immer offensichtlich','p'=>'Wasser kann an einer Stelle eintreten und an einer anderen sichtbar werden. Häufige Ursachen sind beschädigte Ziegel, defekte Anschlüsse, undichte Kehlen oder Probleme an Durchdringungen.'],['h2'=>'Wann der Notdienst sinnvoll ist','p'=>'Bei laufendem Wassereintritt oder nach einem Sturmschaden ist eine kurzfristige Sicherung sinnvoll, um Folgeschäden zu begrenzen.']]],
'dachziegel-beschaedigt'=>['title'=>'Dachziegel beschädigt – wann reicht eine Reparatur?','intro'=>'Einzelne beschädigte Ziegel lassen sich häufig gezielt austauschen. Entscheidend ist, ob es sich um einen lokalen Schaden handelt.','sections'=>[['h2'=>'Wann eine Reparatur meist genügt','items'=>['einzelne gebrochene oder verschobene Ziegel','lokaler Sturmschaden','punktuelle Undichtigkeit ohne größere Feuchtigkeitsspuren']],['h2'=>'Wann mehr zu prüfen ist','items'=>['viele beschädigte Ziegel über die Fläche verteilt','durchfeuchtete Dämmung','beschädigte Unterdeckung','wiederkehrende Schäden an denselben Bereichen']],['h2'=>'Verfügbarkeit passender Ziegel','p'=>'Bei älteren Dächern ist zu prüfen, ob passende Ersatzziegel verfügbar sind. Das kann die Entscheidung zwischen Reparatur und Erneuerung beeinflussen.']]],
'tondachziegel-oder-betondachsteine'=>['title'=>'Tondachziegel oder Betondachsteine?','intro'=>'Beide Materialien werden häufig für Steildächer eingesetzt. Die Wahl hängt von Optik, Konstruktion und persönlichen Anforderungen ab.','sections'=>[['h2'=>'Tondachziegel','p'=>'Gebrannter Ton bietet eine natürliche Optik und viele Form- und Farbvarianten.'],['h2'=>'Betondachsteine','p'=>'Betondachsteine sind robust und in verschiedenen Oberflächen erhältlich.'],['h2'=>'Worauf bei der Auswahl geachtet wird','items'=>['Dachneigung und Dachform','Gewicht und Unterkonstruktion','gewünschte Optik und Farbgebung','Umgebungsbebauung und Vorgaben']]]],
'schiefer-dacheindeckung'=>['title'=>'Schiefer als Dacheindeckung – worauf kommt es an?','intro'=>'Schiefer ist ein Naturprodukt und wird traditionell im Dachdeckerhandwerk verarbeitet. Die Ausführung erfordert Erfahrung.','sections'=>[['h2'=>'Deckarten und Gestaltung','p'=>'Je nach Deckart entstehen sehr unterschiedliche Erscheinungsbilder – von ruhigen, gleichmäßigen Flächen bis zu lebendigen Strukturen.'],['h2'=>'Planungsaspekte','items'=>['Unterkonstruktion und Tragfähigkeit','Dachneigung','Ausbildung von Kehlen, Graten und Anschlüssen','Detaillösungen an Gauben und Kaminen']],['h2'=>'Ausführung','p'=>'Die handwerkliche Ausführung bestimmt bei Schiefer besonders stark das Ergebnis – sowohl optisch als auch technisch.']]],
'flachdach-bitumen-epdm-pvc'=>['title'=>'Flachdach: Bitumen, EPDM oder PVC?','intro'=>'Für die Abdichtung von Flachdächern kommen unterschiedliche Systeme infrage. Welche Lösung passt, hängt vom Bestand und den Anforderungen ab.','sections'=>[['h2'=>'Die Systeme im Überblick','items'=>['Bitumen: bewährt, mehrlagig ausführbar, reparaturfreundlich','EPDM: elastisch, großflächig verlegbar','PVC: leicht, mit verschweißten Nähten']],['h2'=>'Auswahlkriterien','items'=>['vorhandener Untergrund und Bestandsaufbau','Dachgeometrie und Durchdringungen','Nutzung der Dachfläche','Entwässerungssituation']],['h2'=>'Bestand zuerst betrachten','p'=>'Vor der Materialentscheidung sollte geklärt werden, ob eine Reparatur, eine Ergänzung oder ein vollständiger Neuaufbau sinnvoll ist.']]],
'welche-dachdaemmung'=>['title'=>'Welche Dachdämmung ist sinnvoll?','intro'=>'Die passende Dämmvariante ergibt sich aus dem vorhandenen Dachaufbau, der geplanten Nutzung und dem Zeitpunkt der Maßnahme.','sections'=>[['h2'=>'Die Varianten','items'=>['Aufsparrendämmung: von außen, meist mit neuer Dacheindeckung','Zwischensparrendämmung: von innen, begrenzt durch die Sparrenhöhe','Untersparrendämmung: ergänzende Ebene von innen']],['h2'=>'Bauphysik beachten','p'=>'Neben der Dämmstärke sind die luftdichte Ebene, die Dampfbremse und die Anschlussdetails entscheidend für einen funktionierenden Aufbau.'],['h2'=>'Keine pauschalen Versprechen','p'=>'Wie stark sich eine Dämmmaßnahme auswirkt, hängt vom konkreten Gebäude ab. Eine individuelle Betrachtung ist deshalb sinnvoll.']]],
'sturmschaden-am-dach'=>['title'=>'Was tun nach einem Sturmschaden am Dach?','intro'=>'Nach einem Sturm sollte das Dach möglichst zeitnah betrachtet werden – auch wenn zunächst kein Wasser eindringt.','sections'=>[['h2'=>'Sinnvolle erste Schritte','items'=>['Bereich um das Gebäude sichern','Schäden vom Boden aus fotografieren','keine eigenen Arbeiten auf dem Dach','Schaden dokumentieren und melden']],['h2'=>'Worauf zu achten ist','items'=>['verschobene oder fehlende Ziegel','beschädigte Ortgang- und Firstbereiche','gelöste Bleche und Rinnen','Feuchtigkeitsspuren im Dachraum']],['h2'=>'Schnelle Sicherung','p'=>'Eine kurzfristige Sicherung kann helfen, Folgeschäden durch Regen zu begrenzen, bevor die endgültige Reparatur erfolgt.']]],
'dachnotdienst-wann-noetig'=>['title'=>'Wann ist ein Dachnotdienst erforderlich?','intro'=>'Nicht jeder Dachschaden ist ein Notfall. Bei akutem Wassereintritt oder Gefahr für Personen ist schnelles Handeln jedoch wichtig.','sections'=>[['h2'=>'Typische Notfallsituationen','items'=>['laufender Wassereintritt','abgedeckte Dachbereiche nach Sturm','lose Bauteile mit Absturzgefahr','großflächige Schäden an der Dachfläche']],['h2'=>'Was bis dahin hilft','items'=>['Wasser auffangen','gefährdete Bereiche absperren','Schäden dokumentieren','auf eigene Dacharbeiten verzichten']],['h2'=>'Danach folgt die dauerhafte Lösung','p'=>'Nach der Sicherung wird geklärt, welche Reparatur oder welche weitergehende Maßnahme tatsächlich erforderlich ist.']]],
];
$data=$articles[$slug]??null;if(!$data){get_template_part('index');return;}get_header();
?>
<main id="main-content" class="rd-main rd-info-page"><section class="rd-page-hero rd-section--sand"><div class="rd-container"><div class="rd-breadcrumb"><a href="<?php echo esc_url(home_url('/ratgeber/')); ?>">Ratgeber</a><span>›</span><span><?php echo esc_html($data['title']); ?></span></div><p class="rd-eyebrow">Ratgeber</p><h1><?php echo esc_html($data['title']); ?></h1><p class="rd-lead"><?php echo esc_html($data['intro']); ?></p></div></section><div class="rd-container rd-info-layout"><div class="rd-service-content"><?php foreach($data['sections'] as $section):?><section class="rd-content-section"><h2><?php echo esc_html($section['h2']);?></h2><?php if(isset($section['p'])):?><div class="rd-text-block"><?php echo esc_html($section['p']);?></div><?php endif;?><?php if(isset($section['items'])):?><ul class="rd-list"><?php foreach($section['items'] as $item):?><li><?php echo esc_html($item);?></li><?php endforeach;?></ul><?php endif;?></section><?php endforeach;?><div class="rd-service-cta"><strong>Fragen zu Ihrem Dach?</strong><a class="rd-cta-button" href="<?php echo esc_url(home_url('/kontakt/')); ?>">Anfrage senden ↗</a></div></div></div></main>
<?php get_footer(); ?>